version: "2"
services:
  zookeeper:
    image: wurstmeister/kafka:2.11-1.1.1
    command:
      ["zookeeper-server-start.sh", "/opt/kafka/config/zookeeper.properties"]
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOSTNAME}:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
